/**
 * kuristina, a ~~kitchen~~ bathroom sink discord bot
 * Copyright (c) 2025-2026 kyu.re
 * SPDX-License-Identifier: AGPL-2.0-or-later
 */

export interface LanguageInfo {
	readonly name: string;
	readonly flag: string;
}

const LANGUAGE_INFO: Record<string, LanguageInfo> = {
	ACE: { name: "Acehnese", flag: "🇮🇩" },
	AF: { name: "Afrikaans", flag: "🇿🇦" },
	SQ: { name: "Albanian", flag: "🇦🇱" },
	AR: { name: "Arabic", flag: "🇸🇦" },
	AN: { name: "Aragonese", flag: "🇪🇸" },
	HY: { name: "Armenian", flag: "🇦🇲" },
	AS: { name: "Assamese", flag: "🇮🇳" },
	AY: { name: "Aymara", flag: "🇧🇴" },
	AZ: { name: "Azerbaijani", flag: "🇦🇿" },
	BA: { name: "Bashkir", flag: "🇷🇺" },
	EU: { name: "Basque", flag: "🇪🇸" },
	BE: { name: "Belarusian", flag: "🇧🇾" },
	BN: { name: "Bengali", flag: "🇧🇩" },
	BHO: { name: "Bhojpuri", flag: "🇮🇳" },
	BS: { name: "Bosnian", flag: "🇧🇦" },
	BR: { name: "Breton", flag: "🇫🇷" },
	BG: { name: "Bulgarian", flag: "🇧🇬" },
	MY: { name: "Burmese", flag: "🇲🇲" },
	YUE: { name: "Cantonese", flag: "🇭🇰" },
	CA: { name: "Catalan", flag: "🇪🇸" },
	CEB: { name: "Cebuano", flag: "🇵🇭" },
	"ZH-HANS": { name: "Chinese (Simplified)", flag: "🇨🇳" },
	"ZH-HANT": { name: "Chinese (Traditional)", flag: "🇹🇼" },
	ZH: { name: "Chinese", flag: "🇨🇳" },
	HR: { name: "Croatian", flag: "🇭🇷" },
	CS: { name: "Czech", flag: "🇨🇿" },
	DA: { name: "Danish", flag: "🇩🇰" },
	PRS: { name: "Dari", flag: "🇦🇫" },
	NL: { name: "Dutch", flag: "🇳🇱" },
	EN: { name: "English", flag: "🇬🇧" },
	"EN-US": { name: "English (American)", flag: "🇺🇸" },
	"EN-GB": { name: "English (British)", flag: "🇬🇧" },
	EO: { name: "Esperanto", flag: "<:husk:1468079394475081982>" },
	ET: { name: "Estonian", flag: "🇪🇪" },
	FI: { name: "Finnish", flag: "🇫🇮" },
	FR: { name: "French", flag: "🇫🇷" },
	"FR-CA": { name: "French (Canadian)", flag: "🇨🇦" },
	GL: { name: "Galician", flag: "🇪🇸" },
	KA: { name: "Georgian", flag: "🇬🇪" },
	DE: { name: "German", flag: "🇩🇪" },
	"DE-CH": { name: "German (Swiss)", flag: "🇨🇭" },
	EL: { name: "Greek", flag: "🇬🇷" },
	GN: { name: "Guarani", flag: "🇵🇾" },
	GU: { name: "Gujarati", flag: "🇮🇳" },
	HT: { name: "Haitian Creole", flag: "🇭🇹" },
	HA: { name: "Hausa", flag: "🇳🇬" },
	HE: { name: "Hebrew", flag: "🇵🇱" },
	HI: { name: "Hindi", flag: "🇮🇳" },
	HU: { name: "Hungarian", flag: "🇭🇺" },
	IS: { name: "Icelandic", flag: "🇮🇸" },
	IG: { name: "Igbo", flag: "🇳🇬" },
	ID: { name: "Indonesian", flag: "🇮🇩" },
	GA: { name: "Irish", flag: "🇮🇪" },
	IT: { name: "Italian", flag: "🇮🇹" },
	JA: { name: "Japanese", flag: "🇯🇵" },
	JV: { name: "Javanese", flag: "🇮🇩" },
	PAM: { name: "Kapampangan", flag: "🇵🇭" },
	KK: { name: "Kazakh", flag: "🇰🇿" },
	GOM: { name: "Konkani", flag: "🇮🇳" },
	KO: { name: "Korean", flag: "🇰🇷" },
	KMR: { name: "Kurdish (Kurmanji)", flag: "🇮🇶" },
	CKB: { name: "Kurdish (Sorani)", flag: "🇮🇶" },
	KY: { name: "Kyrgyz", flag: "🇰🇬" },
	LA: { name: "Latin", flag: "🌐" },
	LV: { name: "Latvian", flag: "🇱🇻" },
	LN: { name: "Lingala", flag: "🇨🇩" },
	LT: { name: "Lithuanian", flag: "🇱🇹" },
	LMO: { name: "Lombard", flag: "🇮🇹" },
	LB: { name: "Luxembourgish", flag: "🇱🇺" },
	MK: { name: "Macedonian", flag: "🇲🇰" },
	MAI: { name: "Maithili", flag: "🇮🇳" },
	MG: { name: "Malagasy", flag: "🇲🇬" },
	MS: { name: "Malay", flag: "🇲🇾" },
	ML: { name: "Malayalam", flag: "🇮🇳" },
	MT: { name: "Maltese", flag: "🇲🇹" },
	MI: { name: "Maori", flag: "🇳🇿" },
	MR: { name: "Marathi", flag: "🇮🇳" },
	MN: { name: "Mongolian", flag: "🇲🇳" },
	NE: { name: "Nepali", flag: "🇳🇵" },
	NB: { name: "Norwegian Bokmål", flag: "🇳🇴" },
	OC: { name: "Occitan", flag: "🇫🇷" },
	OM: { name: "Oromo", flag: "🇪🇹" },
	PAG: { name: "Pangasinan", flag: "🇵🇭" },
	PS: { name: "Pashto", flag: "🇦🇫" },
	FA: { name: "Persian", flag: "🇮🇷" },
	PL: { name: "Polish", flag: "🇵🇱" },
	"PT-BR": { name: "Portuguese (Brazilian)", flag: "🇧🇷" },
	"PT-PT": { name: "Portuguese (European)", flag: "🇵🇹" },
	PT: { name: "Portuguese (Brazilian)", flag: "🇧🇷" },
	PA: { name: "Punjabi", flag: "🇮🇳" },
	QU: { name: "Quechua", flag: "🇵🇪" },
	RO: { name: "Romanian", flag: "🇷🇴" },
	RU: { name: "Russian", flag: "🇷🇺" },
	SA: { name: "Sanskrit", flag: "🇮🇳" },
	SR: { name: "Serbian", flag: "🇷🇸" },
	ST: { name: "Sesotho", flag: "🇱🇸" },
	SCN: { name: "Sicilian", flag: "🇮🇹" },
	SK: { name: "Slovak", flag: "🇸🇰" },
	SL: { name: "Slovenian", flag: "🇸🇮" },
	ES: { name: "Spanish", flag: "🇪🇸" },
	"ES-419": { name: "Spanish (Latin American)", flag: "🇨🇴" },
	SU: { name: "Sundanese", flag: "🇮🇩" },
	SW: { name: "Swahili", flag: "🇹🇿" },
	SV: { name: "Swedish", flag: "🇸🇪" },
	TL: { name: "Tagalog", flag: "🇵🇭" },
	TG: { name: "Tajik", flag: "🇹🇯" },
	TA: { name: "Tamil", flag: "🇮🇳" },
	TT: { name: "Tatar", flag: "🇷🇺" },
	TE: { name: "Telugu", flag: "🇮🇳" },
	TH: { name: "Thai", flag: "🇹🇭" },
	TS: { name: "Tsonga", flag: "🇿🇦" },
	TN: { name: "Tswana", flag: "🇧🇼" },
	TR: { name: "Turkish", flag: "🇹🇷" },
	TK: { name: "Turkmen", flag: "🇹🇲" },
	UK: { name: "Ukrainian", flag: "🇺🇦" },
	UR: { name: "Urdu", flag: "🇵🇰" },
	UZ: { name: "Uzbek", flag: "🇺🇿" },
	VI: { name: "Vietnamese", flag: "🇻🇳" },
	CY: { name: "Welsh", flag: "🇬🇧" },
	WO: { name: "Wolof", flag: "🇸🇳" },
	XH: { name: "Xhosa", flag: "🇿🇦" },
	YI: { name: "Yiddish", flag: "🇵🇱" },
	ZU: { name: "Zulu", flag: "🇿🇦" },
};

const FALLBACK: LanguageInfo = { name: "Unknown", flag: "🌐" };

export function getLanguageInfo(code: string): LanguageInfo {
	return LANGUAGE_INFO[code.toUpperCase()] ?? { ...FALLBACK, name: code };
}

export function formatLanguage(code: string): string {
	const { name, flag } = getLanguageInfo(code);
	return `${flag} ${name}`;
}
