# https://discord.dev
[discord]
token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0.KMUFsIDTnFmyG3nMiGM6H9FNFUROf3wh7SmqJp-QV30"
application_id = "1459789077221081304"
guild_id = "1479796024909500568"

# personal user discord id
[owner]
id = "111111111111111111"

# emojis
[emojis]
success = "<:bibooSip:1439478822163710064>"
error   = "<:bibooThink:1439478804501237850>"
loading = "<:bibooZzz:1439478767960588351>"

[commands]
default_cooldown_ms = 3_000 # cooldown between command uses per user, in ms
max_mentions = 3 # maximum users a single command can mention

[cache]
context_ttl_ms = 450_000 # how long to keep command context cached, in ms (7.5 min)

[sqlite]
path = "./data/kuristina.sqlite"

[modules]
# permit user accounts to be used
client = false

[modules.commands]
role = true
ping = true
help = true

[modules.markov]
enabled = false
channel_id = "111111111111111111" 
